# Generated by Django 4.2 on 2023-04-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('days_to_first_harvest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateTimeField(verbose_name='date it was planted')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.planttype')),
            ],
        ),
    ]
