# Generated by Django 4.2 on 2023-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='description',
        ),
        migrations.AddField(
            model_name='garden',
            name='lighting',
            field=models.CharField(choices=[('SUNNY', 'Sunny'), ('PARTIAL_SUN', 'Partial Sun'), ('PARTIAL_SHADE', 'Partial Shade'), ('SHADE', 'Shade')], default='SUNNY', max_length=100),
        ),
        migrations.AddField(
            model_name='garden',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
