# Generated by Django 4.2 on 2023-04-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_garden_description_garden_lighting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='lighting',
            field=models.CharField(choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SUN', 'Partial Sun'), ('PARTIAL_SHADE', 'Partial Shade'), ('FULL_SHADE', 'Full Shade')], default='SUNNY', max_length=100),
        ),
    ]
